### ISSUE TITLE
MISRA Addon for cppcheck static analysis

### ISSUE THREAD

**Issue by 0xsninja** [nasa/cFS#338]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [cFS README.md file](https://github.com/nasa/cFS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
Currently the cppcheck static analysis workflow does not include MISRA addons. Adding the MISRA addons allows for a more thorough static analysis check.

**Describe the solution you'd like**
Using the cppcheck addon for MISRA, the current workflow has been modified to include the MISRA addons. 

**Describe alternatives you've considered**
Alternatives might be a separate MISRA check workflow, but this way is more consolidated and easier.

**Additional context**
The cppcheck addon used can be found here: https://github.com/danmar/cppcheck/blob/main/addons/README.md
The MISRA Python addon is here: https://github.com/danmar/cppcheck/blob/main/addons/misra.py

**Requester Info**
Adrian Schalk
m225766@usna.edu
Goddard summer Intern under Ariel Adams
Midshipman, USN, US Naval Academy

**Comment by skliper** [comment]
Is there a way to manage what would throw an error vs be a warning to fix later (or quarantine or whatever)?  Right now we are very "clean" vs the current cppcheck criteria and it's clear anything that gets reported we need to resolve before merge.  If we add in all the MISRA rules without providing another category or separation we may get lost in all the additional information.  Open to ideas/suggestions... right now I see the additional reporting as informational since we don't have hard pass/fail criteria related to those rules yet (we should work that out as part of the future coding standard compliance work!)  Maybe we trigger the workflow manually based on someone committing to review it vs every push?
