### ISSUE TITLE
Non Flight Apps

### ISSUE THREAD

**Issue by blueed9696** [nasa/cFS#785]
I'm trying to build a RF communication app and trying to reference other app codes. However, I could find the apps in cFS repository are non flight applications.

What makes them to become a non flight purpose? Is it because it doesn't have RF system?

**Comment by avan989** [comment]
I think it is a liability thing. Every flight system is different and you would need to configure the app for it and make sure it is a fit for your need.

**Comment by BBinLP** [comment]
It has been our experience that RF communications is very unique from one
mission to the next.  Whether it is due to the transceiver hardware,
multiple antennas, encryption, data rates, or how the hardware is attached
to the spacecraft bus.  Some efforts have been made recently to at least
separate the protocol processing (e.g. - CCSDS standards) from the hardware
interface but that is not always as simple as it sounds either because
special operational circumstances seem to always pop up.

**Comment by dzbaker** [comment]
Closing issue. Please continue in discussions.
